apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "keeper.fullname" . }}
  labels:
    {{- include "keeper.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  schedule: {{ .Values.schedule }}
  {{- if .Values.timeZone }}
  timeZone: {{ .Values.timeZone }}
  {{- end }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit | default 1 }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit| default 3 }}
  jobTemplate:
    spec:
      template:
        spec:
          {{- if .Values.imagePullSecrets }}
          imagePullSecrets:
          {{ toYaml .Values.imagePullSecrets | indent 2 }}
          {{- end }}
          serviceAccountName: {{ include "keeper.serviceAccountName" . }}
          containers:
            - name: {{ .Chart.Name }}
              {{- with .Values.securityContext }}
              securityContext:
                {{- toYaml . | nindent 12 }}
              {{- end }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              {{- with .Values.resources }}
              resources:
                {{- toYaml . | nindent 12 }}
              {{- end }}
              env:
                - name: JIRA_SITE
                  valueFrom:
                    secretKeyRef:
                      key:  jira_site
                      name: {{ include "keeper.secretName" . }}
                - name: JIRA_USER
                  valueFrom:
                    secretKeyRef:
                      key:  jira_user
                      name: {{ include "keeper.secretName" . }}
                - name: JIRA_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key:  jira_password
                      name: {{ include "keeper.secretName" . }}
                {{- range .Values.extraEnv }}
                - name: {{ .name | quote }}
                  value: {{ .value | quote }}
                {{- end }}
          restartPolicy: {{ .Values.restartPolicy }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- if .Values.priorityClassName }}
          priorityClassName: {{ .Values.priorityClassName }}
          {{- end }}
